### ISSUE TITLE
Incompatible with some resource packs

### ISSUE THREAD

**Issue by Barerock** [KermitEmperor/CuriosBackSlot#2]
Sword is put on the front of the model, in third and first person view. Rather funny, except there's no easy customization (live update).

MC: 1.20.1
FPM: 2.3.3
Curios Back Slot: 4.0.4-nc
![image](https://github.com/KermitEmperor/CuriosBackSlot/assets/38869993/976c4647-e0d6-4797-881b-5a5cbb2e1daf)

**Comment by Barerock** [comment]
it's also sideways, probably due to MB-3D pack. This would be fixable by the user with a full XYZ rotation and XYZ axis movement. I see customization is already on the board, but idk what "customization" entails, so here ya go.

**Comment by Barerock** [comment]
Oh! It's actually ALL caused by MB-3D. Not at all an incompatibility with FPM.

**Comment by Barerock** [comment]
https://www.planetminecraft.com/texture-pack/mb3d-items-pack/

**Comment by KermitEmperor** [comment]
This is mostly caused by the model file of the item. Since the mod uses the head slot for the renderer transformations and the renderer system of item frames, it can cause some resource packs to display their items incorrectly (This applies to mods that add Items with custom model). As of now, I do not have a stable solution for handling this and the best method I've found this that to give the players the tools to fix it themselves.

**Comment by Barerock** [comment]
I think that really is the best case scenario, efficient effort and coverage all in one.
